name: Build & Deploy to Github Pages

on:
  push:
    branches: ["master"]

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispacth:

jobs:
  #build job
  deploy:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lastest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run ng -- deploy --repo=https://github.com/Lisander-Bautista/portfolio.git --name="Lisander-Bautista" --email="lixanderinfante@gmail.com" --base-href=/portfolio/
